lib/mattdavis_web/router.ex
defmodule MattdavisWeb.Router do
  use MattdavisWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MattdavisWeb do
    pipe_through :browser # Use the default browser stack

    post "/visitors/new", VisitorController, :create
    get "/", PageController, :index
    get "/masterkey", MythController, :index
    get "/purchase", MythController, :sale
    get "/tutoring", PageController, :tutoring
  end

  # Other scopes may use custom stacks.
  # scope "/api", MattdavisWeb do
  #   pipe_through :api
  # end
end

lib/mattdavis/application.ex
defmodule Mattdavis.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Mattdavis.Repo, []),
      # Start the endpoint when the application starts
      supervisor(MattdavisWeb.Endpoint, []),
      # Start your own worker by calling: Mattdavis.Worker.start_link(arg1, arg2, arg3)
      # worker(Mattdavis.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Mattdavis.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MattdavisWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/mattdavis/attention/attention.ex
defmodule Mattdavis.Attention do
  @moduledoc """
  The Attention context.
  """

  import Ecto.Query, warn: false
  alias Mattdavis.Repo

  alias Mattdavis.Attention.Visitor

  @doc """
  Returns the list of visitors.

  ## Examples

      iex> list_visitors()
      [%Visitor{}, ...]

  """
  def list_visitors do
    Repo.all(Visitor)
  end

  @doc """
  Gets a single visitor.

  Raises `Ecto.NoResultsError` if the Visitor does not exist.

  ## Examples

      iex> get_visitor!(123)
      %Visitor{}

      iex> get_visitor!(456)
      ** (Ecto.NoResultsError)

  """
  def get_visitor!(id), do: Repo.get!(Visitor, id)

  @doc """
  Creates a visitor.

  ## Examples

      iex> create_visitor(%{field: value})
      {:ok, %Visitor{}}

      iex> create_visitor(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_visitor(attrs \\ %{}) do
    %Visitor{}
    |> Visitor.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a visitor.

  ## Examples

      iex> update_visitor(visitor, %{field: new_value})
      {:ok, %Visitor{}}

      iex> update_visitor(visitor, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_visitor(%Visitor{} = visitor, attrs) do
    visitor
    |> Visitor.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Visitor.

  ## Examples

      iex> delete_visitor(visitor)
      {:ok, %Visitor{}}

      iex> delete_visitor(visitor)
      {:error, %Ecto.Changeset{}}

  """
  def delete_visitor(%Visitor{} = visitor) do
    Repo.delete(visitor)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking visitor changes.

  ## Examples

      iex> change_visitor(visitor)
      %Ecto.Changeset{source: %Visitor{}}

  """
  def change_visitor(%Visitor{} = visitor) do
    Visitor.changeset(visitor, %{})
  end
end

lib/mattdavis/attention/visitor.ex
defmodule Mattdavis.Attention.Visitor do
  use Ecto.Schema
  import Ecto.Changeset


  schema "visitors" do
    field :email, :string
    field :name, :string
    field :what, :string

    timestamps()
  end

  @doc false
  def changeset(visitor, attrs) do
    visitor
    |> cast(attrs, [:email, :name, :what])
    |> validate_required([:email, :name, :what])
  end
end

lib/mattdavis/repo.ex
defmodule Mattdavis.Repo do
  use Ecto.Repo, otp_app: :mattdavis

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/mattdavis_web/controllers/myth_controller.ex
defmodule MattdavisWeb.MythController do
	use MattdavisWeb, :controller

	def index(conn, _params) do
	  	IO.puts("**displaying myth page***")
	  	#IO.inspect(Bandstock.GraphicMagic.magic)
	    render conn, "index.html"
	 end

	 def sale(conn, _params) do
	 		IO.puts("**displaying sales page***")

			render conn, "sale.html"
	 end
end

lib/mattdavis_web/controllers/page_controller.ex
defmodule MattdavisWeb.PageController do
  use MattdavisWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def tutoring(conn, _params) do
    render conn, "tutoring.html"
  end

end

lib/mattdavis_web/controllers/visitor_controller.ex
defmodule MattdavisWeb.VisitorController do
  use MattdavisWeb, :controller

  alias Mattdavis.Attention
  alias Mattdavis.Attention.Visitor

  def index(conn, _params) do
    visitors = Attention.list_visitors()
    render(conn, "index.html", visitors: visitors)
  end

  def new(conn, _params) do
    changeset = Attention.change_visitor(%Visitor{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"visitor" => visitor_params}) do
    case Attention.create_visitor(visitor_params) do
      {:ok, visitor} ->
        conn
        |> put_flash(:info, "Sending your content to " <> visitor.email <> " now.")
        |> redirect(to: visitor_path(conn, :show, visitor))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    visitor = Attention.get_visitor!(id)
    render(conn, "show.html", visitor: visitor)
  end

  def edit(conn, %{"id" => id}) do
    visitor = Attention.get_visitor!(id)
    changeset = Attention.change_visitor(visitor)
    render(conn, "edit.html", visitor: visitor, changeset: changeset)
  end

  def update(conn, %{"id" => id, "visitor" => visitor_params}) do
    visitor = Attention.get_visitor!(id)

    case Attention.update_visitor(visitor, visitor_params) do
      {:ok, visitor} ->
        conn
        |> put_flash(:info, "Visitor updated successfully.")
        |> redirect(to: visitor_path(conn, :show, visitor))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", visitor: visitor, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    visitor = Attention.get_visitor!(id)
    {:ok, _visitor} = Attention.delete_visitor(visitor)

    conn
    |> put_flash(:info, "Visitor deleted successfully.")
    |> redirect(to: visitor_path(conn, :index))
  end
end

lib/mattdavis_web/views/error_view.ex
defmodule MattdavisWeb.ErrorView do
  use MattdavisWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/mattdavis_web/views/layout_view.ex
defmodule MattdavisWeb.LayoutView do
  use MattdavisWeb, :view
end

lib/mattdavis_web/views/myth_view.ex
defmodule MattdavisWeb.MythView do
  use MattdavisWeb, :view
end

lib/mattdavis_web/views/page_view.ex
defmodule MattdavisWeb.PageView do
  use MattdavisWeb, :view
end

lib/mattdavis_web/views/visitor_view.ex
defmodule MattdavisWeb.VisitorView do
  use MattdavisWeb, :view
end

lib/mattdavis_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>UI Humanics</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/app.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <!-- Mailchimp! -->
  <script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us17.list-manage.com","uuid":"29992a903616db2478ac082f2","lid":"146ebcab02"}) })</script>

  <script>
  var deadline = new Date("Jul 21, 2018 17:00:00").getTime();
  var x = setInterval(function() {
  var now = new Date().getTime();
  var t = deadline - now;
  var days = Math.floor(t / (1000 * 60 * 60 * 24));
  var hours = Math.floor((t%(1000 * 60 * 60 * 24))/(1000 * 60 * 60));
  var minutes = Math.floor((t % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((t % (1000 * 60)) / 1000);
  document.getElementById("demo").innerHTML = days + " days and " + hours + " hours";
      if (t < 0) {
          clearInterval(x);
          document.getElementById("demo").innerHTML = "Already Left!";
      }
  }, 1000);
  </script>

  <!-- ManyChat -->
  <script src="//widget.manychat.com/801847783318326.js" async="async"></script>
</head>
<body>
  <nav class="white" role="navigation" >
    <div class="nav-wrapper container">
    <span class="brand-logo hide-on-med-and-down">
      <a href="<%= page_path(@conn, :index) %>">
        <img src="images/uilogo.png" alt="UI Logo" height="50px" style="margin-right:15px">
      </a>
      <span class="hide-on-med-and-down">UI Humanics</span>
    </span>

    <span class="brand-logo hide-on-large-only">
      <a href="<%= page_path(@conn, :index) %>">
        <img src="images/uilogo.png" alt="UI Logo" height="20px" style="margin-right:15px">
      </a>
      <span style="font-size:.6em">UI Humanics</span>
    </span>

    <ul class="right hide-on-med-and-down">
      <li><a href="<%= myth_path(@conn, :index)%>">Quest for the Master Key</a></li>
    </ul>
    <ul id="nav-mobile" class="sidenav">
      <li><a href="<%= page_path(@conn, :index) %>">Home</a></li>
      <li><a href="<%= myth_path(@conn, :index)%>">Quest for the Master Key</a></li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <%= render @view_module, @view_template, assigns %>
  <%= render "footer.html" %>
  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="js/app.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/bioep.min.js"></script>
  <script src="js/init.js"></script>


  </body>
</html>

lib/mattdavis_web/templates/layout/footer.html.eex
<footer class="page-footer teal">
  <div class="container">

    <div class="row center">
      <div class="col s12">
        <div class="card white darken-1">
          <div class="card-content black-text">
            <span class="card-title"><h5>UI Humanics</h5></span>
            <p class="card-title text-lighten-4">We help humanity engineer and cultivate authentic personal power.</p>
            <a class="card-title blue-text text-darken-4" target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/UIHumanics">Join Our Facebook Group</a>
            <p></p>
          </div>
        </div>
      </div>
    </div>

  <div class="footer-copyright">
    <div class="container center">
      <i>Reach Matt Davis directly at mattdavis1337@gmail.com</i>
    </div>
  </div>
</footer>

lib/mattdavis_web/templates/myth/index.html.eex
<!DOCTYPE html>
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br />
        <h1 class="center strong white-text text-lighten-4 hide-on-med-and-down">Quest for The Master Key</h1><br>
        <h3 class="center strong white-text text-lighten-4 hide-on-large-only">Quest for The Master Key</h3><br>
        <h5 class="col s12 white-text text-lighten-3 center hide-on-large-only" style="font-weight:bold">Feel relief from doubt. Get help making firm decisions.</h5>

        <div class="row center hide-on-med-and-down">
          <h5 class="col s12 yellow-text text-lighten-4" style="font-weight:bold">Feel relief from doubt. Get help making firm decisions.</h5>
          <h5 class="col s12 yellow-text text-lighten-4" style="font-weight:bold">Alchemize your reluctance and resistance into power.</h5>
          <h5 class="col s12 yellow-text text-lighten-4" style="font-weight:bold">Get help building accountability structures so you follow through.</h5>
          <h5 class="col s12 yellow-text text-lighten-3" style="font-weight:bold">Space is limited. Next wave begins August 1</h5>
        </div>
        <br />
        <div class="row center">
          <a href="<%= myth_path(@conn, :sale)%>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Join Now</a>
        </div>
      </div>
    </div>
    <div class="parallax"><img  class="responsive-img" src="images/purple_paper.jpg" alt="Warm Background"></div>
  </div>

  <div class="row center hide-on-large-only">
    <h5 class="col s12 purple-text text-lighten-3">Alchemize your reluctance and resistance into power.</h5>
    <h5 class="col s12 purple-text text-lighten-3">Get help building accountability structures so you follow through.</h5>
    <h5 class="col s12 purple-text text-lighten-1">Space is limited. Next wave begins August 1</h5>
  </div>

  <div class="container">
    <div class="section">
      <div class="row center">
        <h3>What could you accomplish in one month?</h3>
      </div>
      <div class="row center">
        <img class="responsive-img" src="images/herojourney.png">
      </div>
      <div class="row center">
          <h4 class="col s12 black-text text-darken-4"> <span class="red-text text-darken-4" style="font-size:1.1em">Quest for the Master Key</span></h4>
          <h4 class="col s12 black-text text-darken-4"><span class="blue-text text-darken-4" style="font-size:1.1em">One Month Goal Accelerator Program for Men<span> </h4>
          <h5 class="col s12 black-text text-darken-4">Get coaching support to set ambitious goals.</h5>
          <h5 class="col s12 black-text text-darken-4">Join a group of men who will help you see yourself more clearly.</h5>
          <h5 class="col s12 black-text text-darken-4">Find your personal <span class="red-text text-darken-4"  style="font-size:1.1em">Master Key</span> - the combination of beliefs, mindsets, behaviors, weapons and environments that <span class="red-text text-darken-4"  style="font-size:1.1em">unlock your full potential</span> in any situation</h5>
      </div>
      <div class="row center">
        <hr>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col l2 center"></div>
        <div class="col s12 m12 l8 center">
          <h3 ><i class="mdi-content-send brown-text"></i></h3>
          <h4 class="brown-text">Get 100% Clear on Your Personal Vision</h4>
          <br \>
          <p class="left-align grey-text text-darken-2" style="font-size:1.8em">
            At the beginning of the most satisfying stories, the hero meets a mentor who prepares the hero to face the unknown.
            <br /><br />
            Your Quest for the Master key begins with the <span class="red-text text-darken-4">Call to Adventure</span>.
            <br /><br />
            This is a 1 on 1 coaching call where you will have an important opportunity to reveal your honest truth about what you want, what's holding you back, and to make a plan for the month.
            <br /><br />
            Your mentor will help you <span class="red-text text-darken-4">overcome resistance</span> so you can be <span class="red-text text-darken-4">armed and equipped</span> for this one month journey.
            <br /><br />
          </p>
        </div>
      </div>
    </div>
  </div>

<!--  PARALLAX 2 ********************************************* -->
  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h1 class="center strong white-text text-darken-4 hide-on-med-and-down">Your Journey Begins Here</h1><br>
          <h3 class="center strong white-text text-darken-4 hide-on-large-only">Your Journey Begins Here</h3><br>
        </div>
      </div>
    </div>
    <div class="parallax"><img  class="responsive-img"  src="images/labyrinth.jpg" alt="Unsplashed background img 2"></div>
  </div>

  <div class="row">
    <div class="col l2 center"></div>
    <div class="col s12 m12 l8  center">

      <div class="card-panel" style="font-size:2em">
        <div class="card-panel teal" style="font-size:2em">
          <h3 class="white-text">Quest for the Master Key</h3>
        </div>
          <img  src="<%= static_path(@conn, "/images/masterkey3.jpg") %>">
          <div>You will have <span class="red-text text-darken-4">One Month</span> to complete your quest and find your personal master key.</div>
          <br />
          <a href="<%= myth_path(@conn, :sale)%>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Join Now</a>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col l2 center"></div>
    <div class="col s12 m12 l8 center">
      <h3 ><i class="mdi-content-send brown-text"></i></h3>
      <h4 class="brown-text">What's Included</h4>
      <br />
      <p class="left-align grey-text text-darken-2" style="font-size:1.8em">
        Enlisting in this program starts you on a one month ride. You'll receive:
        <br /><br />
        <div class="row">
          <div class="col l2">
            <p class="left-align grey-text text-darken-2" style="font-size:3em"><i class="material-icons">flash_on</i></p>
          </div>
          <div class="col l10">
            <p class="left-align grey-text text-darken-2" style="font-size:1.8em"><span class="red-text text-darken-3">Your Call to Adventure enrollment call </span>  - A 1 hour phone call with Matt Davis where we go deep into your personal vision, and find out what you truly deeply want out of this life.  </p>
          </div>
        </div>
        <div class="row">
          <div class="col l2">
            <p class="left-align grey-text text-darken-2" style="font-size:3em"><i class="material-icons">flash_on</i></p>
          </div>
          <div class="col l10">
            <p class="left-align grey-text text-darken-2" style="font-size:1.8em"><span class="red-text text-darken-3">Master Key Goal Setting Resources </span>  - These are written and audio resources that will show you how to set a rock solid goal. You will receive tools to help you develop your personal mythos that speaks deeply to your subconscious.
          </div>
        </div>
        <div class="row">
          <div class="col l2">
            <p class="left-align grey-text text-darken-2" style="font-size:3em"><i class="material-icons">flash_on</i></p>
          </div>
          <div class="col l10">
            <p class="left-align grey-text text-darken-2" style="font-size:1.8em"><span class="red-text text-darken-3">Three Orientation Calls </span>  - During these calls you and your mentor will make a plan for your week that leads you closer to your goal.
          </div>
        </div>
        <div class="row">
          <div class="col l2">
            <p class="left-align grey-text text-darken-2" style="font-size:3em"><i class="material-icons">flash_on</i></p>
          </div>
          <div class="col l10">
            <p class="left-align grey-text text-darken-2" style="font-size:1.8em"><span class="red-text text-darken-3">Three Coaching and Accountability circles</span>  - At the end of each week, we come together for an accountability and coaching circle. You and your allies will meet in a 90 minute video call.  You will tell your story for the week, both victories and defeat. Declare and commit to your vision and goals for the next week. </p>
          </div>
        </div>
        <div class="row">
          <div class="col l2">
            <p class="left-align grey-text text-darken-2" style="font-size:3em"><i class="material-icons">flash_on</i></p>
          </div>
          <div class="col l10">
            <p class="left-align grey-text text-darken-2" style="font-size:1.8em"><span class="red-text text-darken-3">Teamwork and Support</span>  - You can text or email your mentor at any time if you need a clue on how to proceed in your journey.
          </div>
        </div>

        <div class="row">
          <div class="col l2">
            <p class="left-align grey-text text-darken-2" style="font-size:3em"><i class="material-icons">flash_on</i></p>
          </div>
          <div class="col l10">
            <p class="left-align grey-text text-darken-2" style="font-size:1.8em"><span class="red-text text-darken-3">Closing Ceremony</span>  - At the end of one month, we will regroup and CELEBRATE LIKE KINGS. Did you find your Master Key? Or is there more work to do? Were you wounded? Did you gain treasure?  How do we become stronger men from this experience? How does this fit into your Personal Mythos and Destiny?
          </div>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col l2 center"></div>
      <div class="col s12 m12 l8 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>


        <div class="card-panel" style="font-size:2em">
            <h3>Quest for the Master Key</h3>
            <img  src="<%= static_path(@conn, "/images/masterkey3.jpg") %>">
            <div>You will have <span class="red-text text-darken-4">one month</span> to complete your quest and find your personal master key.</div>
            <br />
            <a href="<%= myth_path(@conn, :sale)%>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Join Now</a>
        </div>
      </div>
      <div class="col s2 center"></div>
    </div>

lib/mattdavis_web/templates/myth/sale.html.eex
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <h1 class="center strong white-text text-darken-4"></h1><br>
        <h2 class="center white-text"><i class="material-icons">flash_on</i></h2>
        <h4 class="center white-text" style="font-weight:bold">Ready to Begin your Quest?</h4>
      </div>
    </div>
    <div class="parallax"><img class="responsive-img" src="images/bootsonground.jpg" alt="Warm Background"></div>
  </div>

  <div class="container">
    <div class="section">
      <div class="row">
        <h4 class="center red-text text-darken-2" style="font-weight:bold">Your first challenge: </h4>
        <h4 class="center black-text" style="font-weight:bold">Text Matt Davis right now.</h4>
        <h4 class="center black-text" style="font-weight:bold">His Number is (512) 579-8800. Say "I'm ready."</h4>
        <br /><br />
        <h5 class="center black-text" style="font-weight:bold">Matt will call you to set up a free Vision Exploration Call. He'll ask you about your vision, dreams and goals and you'll find out if this program is right for you. </h5>
      </div>
      <div class="row">
        <div class="col l2 center"></div>
        <div class="col s12 m12 l8  center">
          <div class="card-panel" style="font-size:2em">
            <h3>The Portal is Open</h3>
            <img  class="responsive-img" src="<%= static_path(@conn, "/images/portal.jpg") %>">
            <br /><br />
            <div>"As I heal, so I heal the world" -  Michael Hecht</div>
            <div></div>
          </div>
        </div>
        <div class="col s2 center"></div>
      </div>
    </div>
  </div>

lib/mattdavis_web/templates/page/index.html.eex
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="center white-text text-lighten-1 hide-on-med-and-down">Get to your peak mindset<br />every day</h1><br>
      <h5 class="center white-text text-lighten-1 hide-on-large-only">Get to your peak mindset<br />every day</h1><br>
      <div class="row center">
        <h5 class="col s12 light">UI Humanics is like an engineering team for your personality</h5>
      </div>

      <!-- div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Yes</a>
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">No</a>
      </div-->

      <div class="row center hide-on-med-and-down">
        <div class="col s12">
          <div class="card white darken-1">
            <div class="card-content black-text">
              <span class="card-title">The next Quest for the Master Key leaves the village in: <span id="demo" class="strong"></span><br>
                  <a href="<%= myth_path(@conn, :index)%>">Read More</a></span>
              <p></p>
            </div>
          </div>
        </div>
      </div>

      <div class="row center hide-on-large-only">
        <div class="col s12">
          <div class="card white darken-1">
            <div class="card-content black-text">
              <span class="card-title" style="font-size:.9em">Join the Quest for the Master Key: <span id="demo" class="strong"></span><br>
                  <a href="<%= myth_path(@conn, :index)%>">Read More</a></span>
              <p></p>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
  <div class="parallax"><img src="images/teal_paper.jpg" alt="Warm Background"></div>
</div>


<div class="container">
  <div class="section">
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center purple-text darken-4"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Do You Have a Clear Vision?</h5>

          <h5 class="light center">UI Humanics helps you get clear on what YOU truly want. Beyond goals. Do this for yourself and nobody else.  </h5>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center purple-text darken-4"><i class="material-icons">sentiment_dissatisfied</i></h2>
          <h5 class="center">Then What's Stopping You?</h5>

          <h5 class="light center">Notice the limiting beliefs and excuses that are holding you back. We help you make a plan to overcome them.</h5>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center purple-text darken-4"><i class="material-icons">whatshot</i></h2>
          <h5 class="center">Grit and Loving Challenge.</h5>

          <h5 class="light center">Pure honesty that cuts through the haze and loving challenge that keeps your inner fire burning.</h5>
        </div>
      </div>
    </div>

    <div class="row center">
      <div class="col s12">
        <div class="card white darken-1">
          <div class="card-content black-text">
            <span class="card-title">Read <a target="_blank" rel="noopener noreferrer" href="https://medium.com/@mattdavis_3522/the-five-d-words-that-make-some-people-unstoppable-907b97262a99">The Five D-Words that Make Some People Unstoppable</a></span>
            <p></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row center">
      <div class="col s12  center">
        <div class="card white darken-1  center">
          <div class="card-content black-text  center">
            <div class="mcwidget-embed center" data-widget-id="2497639"></div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>